language: generic
version: 'test-{build}'

environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '8'
    - nodejs_version: '10'
platform:
  - x86
  - x64
clone_folder: 'c:\projects\%APPVEYOR_PROJECT_NAME%'
install:
  - npm install
  - npm install winston@2.3.1
  - curl -sLf https://iobroker.net/install.sh | bash -
  - npm i iobroker.bjfreeathome
test_script:
  - echo %cd%
  - node --version
  - npm --version
  - npm test
build: 'off'
